version: '3.7'

x-smart-answers: &smart-answers
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: smart-answers
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
  working_dir: /govuk/smart-answers

services:
  smart-answers-lite:
    <<: *smart-answers

  smart-answers-app:
    <<: *smart-answers
    depends_on:
      - nginx-proxy
      - publishing-api-app
      - static-app
      - content-store-app
      - whitehall-app
    environment:
      VIRTUAL_HOST: smart-answers.dev.gov.uk
      BINDING: 0.0.0.0
    expose:
      - "3000"
    command: bin/rails s --restart
