version: '3.7'

x-support: &support
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: support
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
  working_dir: /govuk/support

services:
  support-lite:
    <<: *support
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis

  support-app: &support-app
    <<: *support
    depends_on:
      - redis
      - nginx-proxy
      - support-api-app
    environment:
      VIRTUAL_HOST: support.dev.gov.uk
      REDIS_URL: redis://redis
      BINDING: 0.0.0.0
    expose:
      - "3000"
    command: bin/rails s --restart
