version: '3.7'

volumes:
  local-links-manager-tmp:

x-local-links-manager: &local-links-manager
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: local-links-manager
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
    - local-links-manager-tmp:/govuk/local-links-manager/tmp
  working_dir: /govuk/local-links-manager

services:
  local-links-manager-lite:
    <<: *local-links-manager
    depends_on:
      - postgres-9.6
    environment:
      DATABASE_URL: "postgresql://postgres@postgres-9.6/local-links-manager"
      TEST_DATABASE_URL: "postgresql://postgres@postgres-9.6/local-links-manager-test"

  local-links-manager-app:
    <<: *local-links-manager
    depends_on:
      - postgres-9.6
      - nginx-proxy
    environment:
      DATABASE_URL: "postgresql://postgres@postgres-9.6/local-links-manager"
      VIRTUAL_HOST: local-links-manager.dev.gov.uk
      HOST: 0.0.0.0
    expose:
      - "3000"
    command: bin/rails s --restart
