version: '3.7'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ./services/nginx-proxy/proxy.conf:/etc/nginx/proxy.conf
    networks:
      default:
        aliases:
          - asset-manager.dev.gov.uk
          - authenticating-proxy.dev.gov.uk
          - calculators.dev.gov.uk
          - calendars.dev.gov.uk
          - collections-publisher.dev.gov.uk
          - collections.dev.gov.uk
          - content-publisher.dev.gov.uk
          - content-store.dev.gov.uk
          - content-tagger.dev.gov.uk
          - draft-calculators.dev.gov.uk
          - draft-calendars.dev.gov.uk
          - draft-collections.dev.gov.uk
          - draft-content-store.dev.gov.uk
          - draft-frontend.dev.gov.uk
          - draft-government-frontend.dev.gov.uk
          - draft-manuals-frontend.dev.gov.uk
          - draft-origin.dev.gov.uk
          - draft-router-api.dev.gov.uk
          - draft-router.dev.gov.uk
          - draft-service-manual-frontend.dev.gov.uk
          - draft-static.dev.gov.uk
          - email-alert-api.dev.gov.uk
          - email-alert-frontend.dev.gov.uk
          - frontend.dev.gov.uk
          - finder-frontend.dev.gov.uk
          - government-frontend.dev.gov.uk
          - govuk-developer-docs.dev.gov.uk
          - govuk-publishing-components.dev.gov.uk
          - info-frontend.dev.gov.uk
          - licence-finder.dev.gov.uk
          - link-checker-api.dev.gov.uk
          - manuals-frontend.dev.gov.uk
          - publisher.dev.gov.uk
          - publishing-api.dev.gov.uk
          - router-api.dev.gov.uk
          - router.dev.gov.uk
          - search-admin.dev.gov.uk
          - search-api.dev.gov.uk
          - search.dev.gov.uk
          - service-manual-frontend.dev.gov.uk
          - short-url-manager.dev.gov.uk
          - signon.dev.gov.uk
          - smart-answers.dev.gov.uk
          - specialist-publisher.dev.gov.uk
          - static.dev.gov.uk
          - support-api.dev.gov.uk
          - support.dev.gov.uk
          - transition.dev.gov.uk
          - travel-advice-publisher.dev.gov.uk
          - whitehall-admin.dev.gov.uk
          - www-origin.dev.gov.uk
          - www.dev.gov.uk
