version: '3.7'

x-govuk-attribute-service-prototype: &govuk-attribute-service-prototype
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: govuk-attribute-service-prototype
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - home:/home/build
  working_dir: /govuk/govuk-attribute-service-prototype

services:
  govuk-attribute-service-prototype-lite:
    <<: *govuk-attribute-service-prototype
    privileged: true
    depends_on:
      - memcached
      - postgres
    environment:
      MEMCACHE_SERVERS: memcached
      DATABASE_URL: "postgresql://postgres@postgres/govuk-attribute-service-prototype"
      ACCOUNT_MANAGER_URL: http://www.login.service.dev.gov.uk
      ACCOUNT_MANAGER_TOKEN: attribute-service-token
      TEST_DATABASE_URL: "postgresql://postgres@postgres/govuk-attribute-service-prototype-test"

  govuk-attribute-service-prototype-app: &govuk-attribute-service-prototype-app
    <<: *govuk-attribute-service-prototype
    depends_on:
      - nginx-proxy
      - postgres
    environment:
      ASSET_HOST: attributes.login.service.dev.gov.uk
      VIRTUAL_HOST: attributes.login.service.dev.gov.uk
      ACCOUNT_MANAGER_URL: http://www.login.service.dev.gov.uk
      ACCOUNT_MANAGER_TOKEN: attribute-service-token
      BINDING: 0.0.0.0
      MEMCACHE_SERVERS: memcached
      DATABASE_URL: "postgresql://postgres@postgres/govuk-attribute-service-prototype"
    expose:
      - "3000"
    command: bin/rails s --restart
