version: '3.7'

x-transition: &transition
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: transition
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
  working_dir: /govuk/transition

services:
  transition-lite:
    <<: *transition
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: "postgresql://postgres@postgres/transition"
      TEST_DATABASE_URL: "postgresql://postgres@postgres/transition-test"
      REDIS_URL: redis://redis

  transition-app: &transition-app
    <<: *transition
    depends_on:
      - nginx-proxy
      - postgres
      - redis
    environment:
      DATABASE_URL: "postgresql://postgres@postgres/transition"
      REDIS_URL: redis://redis
      VIRTUAL_HOST: transition.dev.gov.uk
      HOST: 0.0.0.0
    expose:
      - "3000"
    command: bin/rails s --restart
