version: '3.7'

volumes:
  calculators-tmp:

x-calculators: &calculators
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: calculators
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
    - calculators-tmp:/govuk/calculators/tmp
  working_dir: /govuk/calculators

services:
  calculators-lite:
    <<: *calculators

  calculators-app: &calculators-app
    <<: *calculators
    depends_on:
      - router-app
      - content-store-app
      - static-app
      - nginx-proxy
    environment:
      ASSET_HOST: calculators.dev.gov.uk
      VIRTUAL_HOST: calculators.dev.gov.uk
      HOST: 0.0.0.0
    expose:
      - "3000"
    command: bin/rails s --restart

  calculators-app-live:
    <<: *calculators-app
    depends_on:
      - nginx-proxy
    environment:
      GOVUK_WEBSITE_ROOT: https://www.gov.uk
      PLEK_SERVICE_CONTENT_STORE_URI: https://www.gov.uk/api
      PLEK_SERVICE_STATIC_URI: assets.publishing.service.gov.uk
      VIRTUAL_HOST: calculators.dev.gov.uk
      HOST: 0.0.0.0
