version: '3.7'

x-govuk-developer-docs: &govuk-developer-docs
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: govuk-developer-docs
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - home:/home/build
  working_dir: /govuk/govuk-developer-docs

services:
  govuk-developer-docs-lite:
    <<: *govuk-developer-docs
    environment:
      LANG: "C.UTF-8"

  govuk-developer-docs-app:
    <<: *govuk-developer-docs
    depends_on:
      - nginx-proxy
    environment:
      VIRTUAL_HOST: govuk-developer-docs.dev.gov.uk
    ports:
      - "4567"
    command: bundle exec middleman server --bind-address 0.0.0.0
