version: '3.7'

x-govuk-content-schemas: &govuk-content-schemas
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: govuk-content-schemas
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - home:/home/build
  working_dir: /govuk/govuk-content-schemas

services:
  govuk-content-schemas-lite:
    <<: *govuk-content-schemas

  govuk-content-schemas-app:
    <<: *govuk-content-schemas
    depends_on:
      - nginx-proxy
    environment:
      VIRTUAL_HOST: govuk-content-schemas.dev.gov.uk
      HOST: 0.0.0.0
    expose:
      - "4567"
    command: bundle exec ruby app.rb
