version: '3.7'

volumes:
  feedback-tmp:

x-feedback: &feedback
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: feedback
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
    - feedback-tmp:/govuk/feedback/tmp
  working_dir: /govuk/feedback

services:
  feedback-lite:
    <<: *feedback

  feedback-app: &feedback-app
    <<: *feedback
    depends_on:
      - router-app
      - static-app
      - nginx-proxy
      - support-api-app
      - support-app
    environment:
      ASSET_HOST: feedback.dev.gov.uk
      VIRTUAL_HOST: feedback.dev.gov.uk
      HOST: 0.0.0.0
    expose:
      - "3000"
    command: bin/rails s --restart

  feedback-app-live:
    <<: *feedback-app
    depends_on:
      - nginx-proxy
    environment:
      GOVUK_WEBSITE_ROOT: https://www.gov.uk
      PLEK_SERVICE_CONTENT_STORE_URI: https://www.gov.uk/api
      PLEK_SERVICE_STATIC_URI: assets.publishing.service.gov.uk
      VIRTUAL_HOST: feedback.dev.gov.uk
      HOST: 0.0.0.0
