version: '3.7'

x-email-alert-frontend: &email-alert-frontend
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: email-alert-frontend
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - home:/home/build
  working_dir: /govuk/email-alert-frontend

services:
  email-alert-frontend-lite:
    <<: *email-alert-frontend

  email-alert-frontend-setup:
    <<: *email-alert-frontend
    depends_on:
      - publishing-api-app-e2e
      - nginx-proxy

  email-alert-frontend-app: &email-alert-frontend-app
    <<: *email-alert-frontend
    depends_on:
      - router-app
      - content-store-app
      - static-app
      - email-alert-api-app
      - nginx-proxy
    environment:
      GOVUK_ASSET_ROOT: email-alert-frontend.dev.gov.uk
      VIRTUAL_HOST: email-alert-frontend.dev.gov.uk
      HOST: 0.0.0.0
    ports:
      - "3000"
    command: bin/rails s --restart

  email-alert-frontend-app-live:
    <<: *email-alert-frontend-app
    depends_on:
      - email-alert-api-app
      - nginx-proxy
    environment:
      GOVUK_WEBSITE_ROOT: https://www.gov.uk
      PLEK_SERVICE_CONTENT_STORE_URI: https://www.gov.uk/api
      PLEK_SERVICE_STATIC_URI: assets.publishing.service.gov.uk
      VIRTUAL_HOST: email-alert-frontend.dev.gov.uk
      HOST: 0.0.0.0
