version: '3.7'

x-content-data-admin: &content-data-admin
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: content-data-admin
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
  working_dir: /govuk/content-data-admin

services:
  content-data-admin-lite:
    <<: *content-data-admin
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres@postgres/content-data-admin"
      TEST_DATABASE_URL: "postgresql://postgres@postgres/content-data-admin-test"
