version: '3.7'

x-content-data-admin: &content-data-admin
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: content-data-admin
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - home:/home/build
  working_dir: /govuk/content-data-admin

services:
  content-data-admin-lite:
    <<: *content-data-admin
    privileged: true
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres@postgres/content-data-admin"
      TEST_DATABASE_URL: "postgresql://postgres@postgres/content-data-admin-test"

  content-data-admin-app: &content-data-admin-app
    <<: *content-data-admin
    depends_on:
      - nginx-proxy
      - content-data-api-app
    expose:
      - "3000"
    command: bin/rails s --restart
    environment:
      VIRTUAL_HOST: content-data-admin.dev.gov.uk
      HOST: 0.0.0.0

  content-data-admin-app-live:
    <<: *content-data-admin-app
    environment:
      GOVUK_WEBSITE_ROOT: https://www.gov.uk
      PLEK_SERVICE_CONTENT_STORE_URI: https://www.gov.uk/api
      PLEK_SERVICE_STATIC_URI: assets.publishing.service.gov.uk
      VIRTUAL_HOST: content-data-admin.dev.gov.uk
      HOST: 0.0.0.0