version: '3.7'

x-contacts-admin: &contacts-admin
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: contacts-admin
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
  working_dir: /govuk/contacts-admin

services:
  contacts-admin-lite:
    <<: *contacts-admin
    depends_on:
      - mysql
      - redis
    environment:
      DATABASE_URL: "mysql2://root:root@mysql/contacts_development"
      TEST_DATABASE_URL: "mysql2://root:root@mysql/contacts_test"
      REDIS_HOST: redis

