version: '3.7'

volumes:
  service-manual-publisher-tmp:

x-service-manual-publisher: &service-manual-publisher
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: service-manual-publisher
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
    - service-manual-publisher-tmp:/govuk/service-manual-publisher/tmp
  working_dir: /govuk/service-manual-publisher

services:
  service-manual-publisher-lite:
    <<: *service-manual-publisher
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres@postgres/service-manual-publisher"
      TEST_DATABASE_URL: "postgresql://postgres@postgres/service-manual-publisher-test"
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
