version: '3.7'

x-content-store: &content-store
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: content-store
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
  working_dir: /govuk/content-store

services:
  content-store-lite:
    <<: *content-store
    depends_on:
      - mongo
    environment:
      MONGODB_URI: "mongodb://mongo/content-store"
      TEST_MONGODB_URI: "mongodb://mongo/content-store-test"

  content-store-app: &content-store-app
    <<: *content-store
    depends_on:
      - mongo
      - router-api-app
      - nginx-proxy
    environment:
      MONGODB_URI: "mongodb://mongo/content-store"
      VIRTUAL_HOST: content-store.dev.gov.uk
      HOST: 0.0.0.0
    expose:
      - "3000"
    command: bin/rails s --restart
