version: '3.7'

x-imminence: &imminence
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: imminence
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
  working_dir: /govuk/imminence

services:
  imminence-lite:
    <<: *imminence
    depends_on:
      - mongo
    environment:
      MONGODB_URI: "mongodb://mongo/imminence"
      TEST_MONGODB_URI: "mongodb://mongo/imminence-test"
