version: '3.7'

volumes:
  manuals-publisher-tmp:

x-manuals-publisher: &manuals-publisher
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: manuals-publisher
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
    - manuals-publisher-tmp:/govuk/manuals-publisher/tmp
  working_dir: /govuk/manuals-publisher

services:
  manuals-publisher-lite:
    <<: *manuals-publisher
    depends_on:
      - mongo
    environment:
      MONGODB_URI: "mongodb://mongo/manuals-publisher"
      TEST_MONGODB_URI: "mongodb://mongo/manuals-publisher-test"

