version: '3.7'

volumes:
  publishing-api-tmp:

x-publishing-api: &publishing-api
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: publishing-api
  tty: true
  stdin_open: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
    - publishing-api-tmp:/govuk/publishing-api/tmp
  working_dir: /govuk/publishing-api

services:
  publishing-api-lite:
    <<: *publishing-api
    depends_on:
      - postgres
      - redis
      - rabbitmq
    environment:
      RABBITMQ_EXCHANGE: published_documents
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
      DATABASE_URL: "postgresql://postgres@postgres/publishing-api"
      TEST_DATABASE_URL: "postgresql://postgres@postgres/publishing-api-test"
      REDIS_URL: redis://redis

  publishing-api-app: &publishing-api-app
    <<: *publishing-api
    depends_on:
      - postgres
      - redis
      - nginx-proxy
    environment:
      DATABASE_URL: "postgresql://postgres@postgres/publishing-api"
      REDIS_URL: redis://redis
      VIRTUAL_HOST: publishing-api.dev.gov.uk
      HOST: 0.0.0.0
    expose:
      - "3000"
    command: bin/rails s --restart
