version: '3.7'

x-collections: &collections
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: collections
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - home:/home/build
  working_dir: /govuk/collections

services:
  collections-lite:
    <<: *collections
    privileged: true

  # TODO: doesn't work yet because collections also relies on search-api
  collections-app: &collections-app
    <<: *collections
    depends_on:
      - router-app
      - content-store-app
      - static-app
      - nginx-proxy
    environment:
      ASSET_HOST: collections.dev.gov.uk
      VIRTUAL_HOST: collections.dev.gov.uk
      HOST: 0.0.0.0
      FEATURE_FLAG_ACCOUNTS: "enabled"
    expose:
      - "3000"
    command: bin/rails s --restart

  collections-app-live:
    <<: *collections-app
    depends_on:
      - nginx-proxy
    environment:
      GOVUK_WEBSITE_ROOT: https://www.gov.uk
      PLEK_SERVICE_CONTENT_STORE_URI: https://www.gov.uk/api
      PLEK_SERVICE_SEARCH_URI: https://www.gov.uk/api
      PLEK_SERVICE_STATIC_URI: assets.publishing.service.gov.uk
      VIRTUAL_HOST: collections.dev.gov.uk
      HOST: 0.0.0.0
      FEATURE_FLAG_ACCOUNTS: "enabled"
