version: '3.7'

volumes:
  specialist-publisher-tmp:

x-specialist-publisher: &specialist-publisher
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: specialist-publisher
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
    - specialist-publisher-tmp:/govuk/specialist-publisher/tmp
  working_dir: /govuk/specialist-publisher

services:
  specialist-publisher-lite:
    <<: *specialist-publisher
    depends_on:
      - mongo-3.6
      - redis
    environment:
      MONGODB_URI: "mongodb://mongo-3.6/specialist-publisher"
      TEST_MONGODB_URI: "mongodb://mongo-3.6/specialist-publisher-test"
      REDIS_URL: redis://redis

  specialist-publisher-app: &specialist-publisher-app
    <<: *specialist-publisher
    depends_on:
      - mongo-3.6
      - redis
      - nginx-proxy
      - publishing-api-app
      - asset-manager-app
      - email-alert-api-app
      - specialist-publisher-worker
    environment:
      MONGODB_URI: "mongodb://mongo-3.6/specialist-publisher"
      REDIS_URL: redis://redis
      VIRTUAL_HOST: specialist-publisher.dev.gov.uk
      HOST: 0.0.0.0
    expose:
      - "3000"
    command: bin/rails s --restart

  specialist-publisher-worker:
    <<: *specialist-publisher
    depends_on:
      - mongo-3.6
      - redis
      - publishing-api-app
      - asset-manager-app
    environment:
      MONGODB_URI: "mongodb://mongo-3.6/specialist-publisher"
      REDIS_URL: redis://redis
    command: bundle exec sidekiq -C ./config/sidekiq.yml
