version: '3.7'

x-licence-finder: &licence-finder
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: licence-finder
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
  working_dir: /govuk/licence-finder

services:
  licence-finder-lite: &licence-finder-lite
    <<: *licence-finder
    depends_on:
      - mongo
      - elasticsearch6
    environment:
      MONGODB_URI: "mongodb://mongo/licence-finder_development"
      TEST_MONGODB_URI: "mongodb://mongo/licence-finder_test"
      ELASTICSEARCH_URI: http://elasticsearch6:9200

  licence-finder-app: &licence-finder-app
    <<: *licence-finder
    depends_on:
      - mongo
      - redis
      - static-app
      - elasticsearch6
      - content-store-app
      - nginx-proxy
    environment:
      REDIS_URL: redis://redis
      VIRTUAL_HOST: licence-finder.dev.gov.uk
      MONGODB_URI: "mongodb://mongo/licence-finder_development"
      ELASTICSEARCH_URI: http://elasticsearch6:9200
      PLEK_SERVICE_CONTENT_STORE_URI: https://www.gov.uk/api
      HOST: 0.0.0.0
    expose:
      - "3000"
    command: bin/rails s --restart

  licence-finder-app-live:
    <<: *licence-finder-app
    depends_on:
      - mongo
      - nginx-proxy
    environment:
      MONGODB_URI: "mongodb://mongo/licence-finder_development"
      PLEK_SERVICE_SEARCH_URI: https://www.gov.uk/api
      GOVUK_WEBSITE_ROOT: https://www.gov.uk
      PLEK_SERVICE_CONTENT_STORE_URI: https://www.gov.uk/api
      PLEK_SERVICE_STATIC_URI: assets.publishing.service.gov.uk
      VIRTUAL_HOST: licence-finder.dev.gov.uk
      HOST: 0.0.0.0
