version: '3.7'

x-static: &static
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: static
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - home:/home/build
  working_dir: /govuk/static

services:
  static-lite:
    <<: *static

  static-app: &static-app
    <<: *static
    depends_on:
      - redis
      - nginx-proxy
    environment:
      REDIS_URL: redis://redis
      GOVUK_ASSET_ROOT: static.dev.gov.uk
      VIRTUAL_HOST: static.dev.gov.uk
      HOST: 0.0.0.0
    ports:
      - "3000"
    command: bin/rails s --restart

  static-app-draft:
    <<: *static-app
    depends_on:
      - redis
      - nginx-proxy
    environment:
      REDIS_URL: redis://redis
      GOVUK_ASSET_ROOT: draft-static.dev.gov.uk
      VIRTUAL_HOST: draft-static.dev.gov.uk
      HOST: 0.0.0.0
