version: '3.7'

x-whitehall: &whitehall
  build:
    context: .
    dockerfile: projects/whitehall/Dockerfile
  image: whitehall
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
  working_dir: /govuk/whitehall

services:
  whitehall-lite:
    <<: *whitehall
    depends_on:
      - mysql
      - redis
    environment:
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
      DATABASE_URL: "mysql2://root:root@mysql/whitehall_development"
      TEST_DATABASE_URL: "mysql2://root:root@mysql/whitehall_test"
      REDIS_URL: redis://redis

  whitehall-app: &whitehall-app
    <<: *whitehall
    depends_on:
      - mysql
      - redis
      - static-app
      - nginx-proxy
      - asset-manager-app
      - publishing-api-app
    environment:
      DATABASE_URL: "mysql2://root:root@mysql/whitehall_development"
      REDIS_URL: redis://redis
      VIRTUAL_HOST: whitehall-admin.dev.gov.uk, whitehall-frontend.dev.gov.uk
      HOST: 0.0.0.0
    expose:
      - "3000"
    # Change to 'bin/rails --restart' when rails >= 5.2
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rails s"
